owner: ReyWins
repo: happeningnow-status

sites:
  - name: Happening Now (Prod Site)
    url: https://happening-now.netlify.app

status-website:
  cname: status.happeningnow.news
  baseUrl: /
  name: Happening Now Status
  introTitle: "Happening Now Status"
  introMessage: "Live uptime and incident reporting for Happening Now."
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://happening-now.netlify.app
    - title: GitHub
      href: https://github.com/ReyWins/happeningnow-status
