owner: ReyWins
repo: happeningnow-status

sites:
  - name: Happening Now (Main Site)
    url: https://happeningnow.news
    maxResponseTime: 10000

  - name: Health - Core Runtime
    url: https://happeningnow.news/api/healthz
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200

  # Providers/adapters: should be FAST and must NOT depend on fetching live stories
  - name: Provider - GDELT
    url: https://happeningnow.news/api/health/gdelt
    maxResponseTime: 4000
    expectedStatusCodes:
      - 200
      - 204

  - name: Provider - News API.ai
    url: https://happeningnow.news/api/health/newsapi-ai
    maxResponseTime: 4000
    expectedStatusCodes:
      - 200
      - 204

  - name: Provider - News Media
    url: https://happeningnow.news/api/health/newsmedia
    maxResponseTime: 4000
    expectedStatusCodes:
      - 200
      - 204

  - name: Adapter - Bluesky
    url: https://happeningnow.news/api/health/bluesky
    maxResponseTime: 4000
    expectedStatusCodes:
      - 200
      - 204

status-website:
  cname: status.happeningnow.news
  baseUrl: /
  name: Happening Now Status
  introTitle: "Happening Now Status"
  introMessage: "Live uptime and adapter availability for Happening Now."
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://happeningnow.news
    - title: GitHub
      href: https://github.com/ReyWins/happeningnow-status
